# Generated by Django 2.0.6 on 2018-06-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kebaby_lokale',
            name='localization_x',
        ),
        migrations.RemoveField(
            model_name='kebaby_lokale',
            name='localization_y',
        ),
        migrations.AddField(
            model_name='kebaby_lokale',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
