# Generated by Django 2.0.6 on 2018-06-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab', '0002_auto_20180617_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebaby_dania',
            name='avg_ref',
            field=models.FloatField(default=0),
        ),
    ]
