# Generated by Django 2.0.6 on 2018-06-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab', '0003_kebaby_dania_avg_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inne_dania',
            name='photo_ref',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='kebaby_dania',
            name='photo_ref',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='kebaby_lokale',
            name='photo_ref',
            field=models.CharField(max_length=1000),
        ),
    ]
