# Generated by Django 2.0.6 on 2018-06-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab', '0004_auto_20180617_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inne_dania',
            name='overall_rate',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=6),
        ),
    ]
