# Generated by Django 2.0.6 on 2018-06-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab', '0005_auto_20180620_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inne_dania',
            name='overall_rate',
            field=models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=0),
        ),
    ]
